model:
  in_channels: 1
  out_channels: 1
  num_groups: 8
  conv_groups: 1
  width_per_group: 64
  padding: !!null
  activation: "ReLU"
  name: "resnet18"
  zero_init_residual: False
  replace_stride_with_dilation: !!null