model:
  feature_maps: 64
  in_channels: 1
  out_channels: 1
  num_levels: 4

  encoder:
    conv_kernel_size: 3
    pool_kernel_size: 2
    pool_type: "MaxPool3d"
    num_groups: 8
    padding: !!python/tuple [1, 1, 1, 1, 1, 1]
    activation: "ReLU"

  decoder:
    interpolation: True
    conv_kernel_size: 3
    pool_kernel_size: 2
    pool_type: "MaxPool3d"
    num_groups: 8
    padding: !!python/tuple [1, 1, 1, 1, 1, 1]
    activation: "ReLU"
    scale_factor: !!python/tuple [2, 2, 2] # Used as the multiplier for the image H/W/D in torch.nn.Upsample or as stride in case of ConvTranspose3d, must reverse the MaxPool3d operation from the corresponding encoder.


